export const COMIC_CHANGE_DISPLAY_IMAGE = 'COMIC_CHANGE_DISPLAY_IMAGE';
export const COMIC_CHANGE_SCALE = 'COMIC_CHANGE_SCALE';
export const COMIC_CLICK_DRAW_PEN = 'COMIC_CLICK_DRAW_PEN';
export const COMIC_CHANGE_COLOR = 'COMIC_CHANGE_COLOR';
export const COMIC_ADD_COMMENTS = 'COMIC_ADD_COMMENTS';
export const COMIC_DRAG_MOVE = 'COMIC_DRAG_MOVE';